### ISSUE TITLE
Question? Muxer development.

### ISSUE THREAD

**Issue by SonnyWalkman** [video-audio/va-ts#6]
Howdy,
Not sure if any of the MPEGTS muxing is working from what I can see in the code?
If so, and I'm missing something, do you have a working example of muxing video, audio and producing the SI tables into the TS stream?
Can the muxer operating via fifo's and not rely an files as input and output?

Cheers

**Comment by vany-egorov** [comment]
Hello, @SonnyWalkman!

Library provides only demuxer :(

Thanks!
